const VOWELS = new Set(['a', 'e', 'i', 'o', 'u',
    'á', 'é', 'í', 'ó', 'ú',
    'ĕ', 'ü',
    'à', 'ä', 'ò',
]);

const PREDEFINED_ALJAMIADO = {
    'almohada':'اَلْمُخَدَّة',
    'elixir':'اَلْإكْسِيٗرْ',
    'alcohol':'اَلْكُحُلْ',
    'sandía':'سَنْدِيَّة',
    'tarea':'طَرِيٗحَة',
    'cifra':'صِفْرَ',
    'albahaca':'اَلْبَحَقَ',
    'asesino':'حَشَاشِيٗنُ',
    'taza':'طَاسَ',
    'limón':'لِيٗمُوٗنْ',
    'algodón':'اَلْقُطُنْ',
    'azúcar':'اَلْسُّكَّرْ',
    'árabe':'عَرَبَا',
    'arábigo':'عَرَبِغُ',
    'arábiga':'عَرَبِغُ',
};
const PREDEFINED_SPANISH = {
    'haber':'aber',
    'ha':'a',
    'he':'e',
    'has':'as',
    'hay':'ay',
    'ha':'a',
    'hemos':'emos',
    'habéis':'abéis',
    'han':'an',
    'había':'abía',
    'habrá':'abrá',
    'habían':'abían',
    'habría':'abría',
    'habrían':'abrían',
    'hubiera':'ubiera',
    'hubieras':'ubieras',
    'hubieran':'ubieran',
    'haya':'aya',
    'hayan':'ayan',
    'hubo':'ubo',
    'hora':'ora',
    'horas':'oras',
    'christiano':'cristiano',
    'christiana':'cristiana',
    'christianos':'cristianos',
    'christianas':'cristianas',
}
const CONS_MAP_ALJAMIADO = {
    'b':'ب',
    'p':'بّ',
    't':'ت',
    'j':'ج',
    'č':'جّ',
    'D':'د',
    'd':'ذ',
    'r':'ر',
    'R':'رّ',
    'z':'ز',
    'ç':'س',
    's':'ش',
    'x':'شّ',
    'g':'غ',
    'f':'ف',
    'k':'ک',
    'l':'ل',
    'L':'لّ',
    'm':'م',
    'n':'ن',
    'ñ':'نّ',
    'w':'و',
    'h':'ه',
    'y':'ي',
};
const VOW_MAP_ALJAMIADO = {
    'a':'َ',
    'e':'َا',
    'i':'ِ',
    'u':'ُ',
    'é':'َاَا',
    'á':'َأَ',
    'ú':'ُؤُ'
};
const VOW_MAP_2_ALJAMIADO = {
    'a':'اَ',
    'e':'ءَا',
    'i':'اِ',
    'u':'اُ',
    'é':'اَا',
    'á':'اَأَ',
    'ú':'اُؤُ'
};

const PREDEFINED_JAWI = {
    'ada':'اد',
    'di':'د',
    'dia':'دي',
    'dan':'دان',
    'ia':'اي',
    'jika':'جک',
    'juga':'جوݢ',
    'ke':'ک',
    'lima':'ليم',
    'kita':'كيت',
    'mereka':'مريک',
    'ini':'اين',
    'itu':'ايت',
    'pada':'ڤد',
    'suka':'سوک',
    'tiga':'تيݢ',
    'saat':'ساعت',
    'hakikat':'حقيقت',
};
const CONS_MAP_JAWI = {
    'b':'ب',
    't':'ت',
    'j':'ج',
    'c':'چ',
    'K':'خ',
    'd':'د',
    'r':'ر',
    'z':'ز',
    's':'س',
    'š':'ش',
    'ŋ':'ڠ',
    'f':'ف',
    'p':'ڤ',
    'q':'ق',
    'k':'ک',
    'g':'ݢ',
    'l':'ل',
    'm':'م',
    'n':'ن',
    'w':'و',
    'v':'ۏ',
    'h':'ه',
    'y':'ي',
    'ñ':'ڽ',
    'X':'خ',
    '`':'ء'
};
const VOW_MAP_1_JAWI = {
    'a':'ا',
    'é':'اي',
    'e':'ا',
    'i':'اي',
    'u':'او',
    'à':'اءي',
    'ä':'اءو',
    'ò':'اووي',
    'ì':'أ'
};
const VOW_MAP_OPEN_JAWI = {
    'a':'ا',
    'é':'ي',
    'e':'',
    'i':'ي',
    'u':'و',
    'à':'اي',
    'ä':'او',
    'ò':'وي',
    'ì':'أ'
};
const VOW_MAP_CLOSED_JAWI = {
    'a':'',
    'é':'ي',
    'e':'',
    'i':'ي',
    'u':'و',
    'à':'اءي',
    'ä':'اءو',
    'ò':'وءي',
    'ì':'أ'
};
const VOW_MAP_2_JAWI = {
    'a':'ا',
    'é':'ي',
    'e':'ی',
    'i':'ي',
    'u':'و',
    'à':'اي',
    'ä':'او',
    'ò':'وي',
    'ì':'أ'
};

const CONS_MAP_OTTOMAN = {
    'b':'ب',
    'p':'پ',
    't':'ت',
    'c':'ج',
    'ç':'چ',
    'j':'ژ',
    'd':'د',
    'r':'ر',
    'z':'ز',
    's':'س',
    'S':'ص',
    'ş':'ش',
    'T':'ط',
    'G':'غ',
    'f':'ف',
    'q':'ق',
    'k':'ك',
    'l':'ل',
    'm':'م',
    'n':'ن',
    'v':'و',
    'h':'ه',
    'y':'ی',
    // 'ñ':'ڭ',
};
const VOW_MAP_1_OTTOMAN = {
    'a':'آ',
    'ı':'ا',
    'o':'او',
    'u':'او',
    'e':'ا',
    'i':'ای',
    'ö':'او',
    'ü':'او',
    'â':'آ',
    'û':'او',
    '0':''
};
const VOW_MAP_MID_OTTOMAN = {
    'a':'ا',
    'ı':'',
    'o':'و',
    'u':'و',
    'e':'',
    'i':'ی',
    'ö':'و',
    'ü':'و',
    'â':'ا',
    'û':'و',
    '0':''
};
const VOW_MAP_2_OTTOMAN = {
    'a':'ه',
    'ı':'ی',
    'o':'و',
    'u':'و',
    'e':'ه',
    'i':'ی',
    'ö':'و',
    'ü':'و',
    'â':'ا',
    'û':'و',
    '0':''
};
const PREDEFINED_OTTOMAN = {
    'bir':'بر',
    've':'و',
    'gibi':'كبی',
    'daha':'دها',
    'dahi':'دخی',
    'vermek':'ویرمك',
    'ama':'اما',
    'kadar':'قدر',
    'qadar':'قدر',
    'insan':'انسان',
    'değil':'دكل',
    'ara':'آرا',
    'ki':'كه',
    'zaman':'زمان',
    'çocuk':'چقجق',
    'çocuq':'چقجق',
    'kalmak':'قلمق',
    'qalmaq':'قلمق',
    'siz':'سز',
    'kadın':'قادین',
    'ev':'أو',
    'hane':'خانه',
    'hoş':'خوش',
    'dünya':'دنیا',
    'aynı':'عینی',
    'veya':'ویا',
    'adam':'آدم',
    'kitap':'کتاب',
    'bütün':'بتون',
    'hakikat':'حقیقت',
    'haqiqat':'حقیقت',
    'osman':'عثمان',
};
const PREDEFINED_TURKISH = {
    'istemek':'estemek',
    'yıl':'yil',
    'çıkmak':'çiqmak',
    'biz':'bez',
    'iyi':'iyü',
    'yeni':'yeñi',
    'önce':'öñce',
    'şekil':'şekl',
    'dört':'d0rt',
    'türk':'t0rk',
    'türkçe':'t0rkce',
    'dil':'d0l',
    'şehir':'şeher',
    'kelime':'keleme',
    'teşekkür':'teşek0r',
    'istanbul':'estanbul',
};

const I18N = {
    'en': {
        'placeholder': 'Type in $1'
    },
    'es': {
        'placeholder': 'Escribe en $1'
    },
};